
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 3/27/2009 9:53:21 AM
//----------------------------------------------------

namespace NMapi.Gateways.IMAP
 {

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public const int UNSUBSCRIBE = 28;
  public const int STATUS = 26;
  public const int NOOP = 17;
  public const int FETCH_ATT = 52;
  public const int CREATE = 19;
  public const int NUMBER = 49;
  public const int CRLF = 11;
  public const int LITERAL = 46;
  public const int FETCH_MSG_TEXT_HEADERLIST_KEY = 56;
  public const int FETCH_ATT_BODY_PEEK = 54;
  public const int APPEND = 18;
  public const int RBRACK = 6;
  public const int ASTRING = 42;
  public const int FLAG_KEY = 58;
  public const int BACKSLASH = 2;
  public const int QUOTED = 45;
  public const int STORE = 37;
  public const int LSUB = 23;
  public const int RPARENT = 3;
  public const int EXAMINE = 21;
  public const int LIST_MAILBOX = 43;
  public const int CLOSE = 33;
  public const int LPARENT = 4;
  public const int SP = 10;
  public const int FETCH_MSG_TEXT_SINGLE = 55;
  public const int FLAG_SIGN = 59;
  public const int SUBSCRIBE = 27;
  public const int DATE_TIME = 44;
  public const int NZ_NUMBER = 48;
  public const int DOT = 9;
  public const int UID = 38;
  public const int SELECT = 25;
  public const int EOF = 0;
  public const int SEARCH = 39;
  public const int LOGOUT = 16;
  public const int SECTION_TEXT_MIME = 57;
  public const int DELETE = 20;
  public const int OTHER = 50;
  public const int LBRACK = 5;
  public const int FETCH_ARG_PRIM = 51;
  public const int STARTTLS = 31;
  public const int LIST = 22;
  public const int FETCH = 36;
  public const int STAR = 14;
  public const int TAG = 47;
  public const int RENAME = 24;
  public const int COLON = 12;
  public const int LESSTHAN = 7;
  public const int FETCH_ATT_BODY = 53;
  public const int STATUS_ATT = 60;
  public const int CHECK = 32;
  public const int X_COMMAND = 40;
  public const int CAPABILITY = 15;
  public const int ATOM = 41;
  public const int COMMA = 13;
  public const int error = 1;
  public const int AUTHENTICATE = 30;
  public const int EXPUNGE = 34;
  public const int GREATERTHAN = 8;
  public const int COPY = 35;
  public const int LOGIN = 29;
	}
}
