<?xml version="1.0"?>
<!--
//
// openmapi.org - NMapi C# Mapi API - xdrgen.xsl
//
// Copyright 2008 Topalis AG
//
// Author: Johannes Roith <johannes@jroith.de>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
//-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" omit-xml-declaration="yes" />

<xsl:include href="../common.xsl" />
<xsl:include href="xdr_data.xsl" />
<xsl:include href="xdr_calls.xsl" />

<xsl:template match="/definitions">
//
// DO NOT EDIT!
// This file was autogenerated.
//

using System;
using System.IO;
using System.Diagnostics;
using System.Collections.Generic;
using System.Net;
using System.Runtime.Serialization;

using NMapi.Interop;
using CompactTeaSharp;
using CompactTeaSharp.Server;

using NMapi;
using NMapi.Flags;
using NMapi.Events;
using NMapi.Properties;
using NMapi.Table;

<xsl:apply-templates select="namespace" />
<xsl:apply-templates select="program" />
</xsl:template>

<xsl:template match="namespace">
	namespace <xsl:value-of select="@name" /> {
		<xsl:apply-templates select="class|enum" />
	}
</xsl:template>

</xsl:stylesheet>