//
// openmapi.org - NMapi C# Mapi API - NativeBody.cs
//
// Copyright 2009-2010 Topalis AG
//
// Author: Johannes Roith <johannes@jroith.de>
//
// This is free software; you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation; either version 2.1 of
// the License, or (at your option) any later version.
//
// This software is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this software; if not, write to the Free
// Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
// 02110-1301 USA, or see the FSF site: http://www.fsf.org.
//

using System;

namespace NMapi.Flags {

	/// <summary>The possible values of Property.NativeBody.</summary>
	/// <remarks>
	///  This property may be generated by the server and, if present, 
	///  defines the type of body that should be used by the client. 
	///  This improves performance, since the "Best Body Algorithm" does not 
	///  have to be used in this case.
	/// </remarks>
	public enum NativeBody
	{

		/// <summary>The property is undefined or the native body unknown to the server.</summary>
		Undefined = 0,

		/// <summary>The native body is stored as plain text in Property.Body.</summary>
		PlainText,

		/// <summary>The native body is stored in Property.RtfCompressed.</summary>
		RtfCompressed,

		/// <summary>The native body is in HTML format, stored in OutlookProperty.Html.</summary>
		Html,

		/// <summary>TODO: document.</summary>
		ClearSigned
	}

}
