<?xml version="1.0"?>
<!--
//
// openmapi.org - OpenMapi Proxy Server - remote_call.xsl
//
// Copyright 2009 Topalis AG
//
// Author: Johannes Roith <johannes@jroith.de>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
//-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" omit-xml-declaration="yes" />

<xsl:template match="/interfaces">
//
// DO NOT EDIT!
// This file was autogenerated.
//

using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

using System.ServiceModel;

using NMapi;
using NMapi.Flags;
using NMapi.Events;
using NMapi.Properties;
using NMapi.Properties.Special;
using NMapi.Table;

namespace NMapi {

	public enum RemoteCall
	{
			<xsl:apply-templates select="interface/method|interface/property" />
	}
	
}
</xsl:template>

<xsl:template match="method|property">
	
	<xsl:variable name="methodName">
		<xsl:choose>
			<xsl:when test="@rpcId != ''">
				<xsl:value-of select="@rpcId" />
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="@id" />
			</xsl:otherwise>
		</xsl:choose>
	</xsl:variable>
	
	<xsl:value-of select="parent::node()/@id" />_<xsl:value-of select="normalize-space ($methodName)" />, 
</xsl:template>

</xsl:stylesheet>