<?xml version="1.0"?>
<!--
//
// openmapi.org - NMapi C# Mapi API - errors.xsl
//
// Copyright 2009 Topalis AG
//
// Author: Johannes Roith <johannes@jroith.de>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
//-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" omit-xml-declaration="yes" />
<xsl:include href="../../../Data/xslt/common.xsl" />

<xsl:template match="/errors">
//
// DO NOT EDIT!
// This file was autogenerated.
//

using System;
using System.IO;

using NMapi;
using NMapi.Flags;
using NMapi.Events;
using NMapi.Properties;
using NMapi.Table;

namespace NMapi.Flags {

	public static partial class Error
	{
		<xsl:for-each select="error|warn">
			/// &lt;summary&gt;Error-Code for the MAPI-Error '<xsl:value-of select="@classicName" />'.&lt;/summary&gt;
			public const int <xsl:value-of select="@name" /> = unchecked ((int) <xsl:value-of select="@id" />);
		</xsl:for-each>
		
		public static string GetErrorName (int hresult)
		{
			switch (hresult) {
				<xsl:for-each select="error|warn">
					case <xsl:value-of select="@name" />: return "<xsl:value-of select="@classicName" />" + GetDescriptivePostFix ("<xsl:value-of select="@name" />"); 
				</xsl:for-each>
				default: return "(no error description)";
			}
		}
	}

}
</xsl:template>
</xsl:stylesheet>
