<?xml version="1.0"?>
<!--
//
// openmapi.org - NMapi C# Mapi API - named.xsl
//
// Copyright 2009 Topalis AG
//
// Author: Johannes Roith <johannes@jroith.de>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
//-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" omit-xml-declaration="yes" />
<xsl:include href="../../../Data/xslt/common.xsl" />

<xsl:template match="/properties">
//
// DO NOT EDIT!
// This file was autogenerated.
//

using System;
using System.IO;

using NMapi;
using NMapi.Flags;
using NMapi.Events;
using NMapi.Properties;
using NMapi.Table;

namespace <xsl:value-of select="@namespace" /> {

	/// &lt;summary&gt;
	///  Contains the known property tag constants.
	/// &lt;/summary&gt;
	public static class <xsl:value-of select="@class" />
	{
		<xsl:for-each select="guid/named">
			/// &lt;summary&gt;
			///  A strongly-typed '<xsl:value-of select="@name" />' named property.
			/// &lt;/summary&gt;
			public static readonly 
				<xsl:call-template name="map-type"><xsl:with-param name="type" select="@type" /></xsl:call-template><xsl:text>PropertyNamedPropertyDef </xsl:text>
				<xsl:value-of select="@name" /> = new <xsl:call-template name="map-type"><xsl:with-param name="type" select="@type" /></xsl:call-template>PropertyNamedPropertyDef (
					<xsl:value-of select="parent::node()/@name" />, <xsl:value-of select="@id" />); 
		</xsl:for-each>
	}

}
</xsl:template>
</xsl:stylesheet>
